In [ ]:
import pandas as pd
import os
os.getcwd()
os.listdir()
# os.makedirs("New Folder")
os.listdir()

['data_science.ipynb', 'New Folder', 'StudentsPerformance.csv']

In [ ]:
import pandas as pd
import numpy as np

# creating a dataframe from an array

In [ ]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])

# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
             columns=['col1', 'col2'])

# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# creating a dataframe from a dictionary

In [ ]:
# lists used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [2223345, 2345678, 8984543, 78452436]

# storing lists within a dictionary
dict_states = {'States': states, 'Population': population}

# creating the dataframe
df_population = pd.DataFrame(dict_states)

# showing the DataFrame
df_population

       States  Population
0  California     2223345
1       Texas     2345678
2     Florida     8984543
3    New York    78452436

Creating a DataFrame from a csv file

In [ ]:
# reading the csv file
df_exams = pd.read_csv("StudentsPerformance.csv")

# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
# show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [ ]:
# display n rows
pd.set_option('display.max_rows', 1000)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# Attributes in Data Science

In [ ]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [ ]:
# getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
# getting access to the column attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
# data types of each column
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

# Methods in Data Science

In [ ]:
# showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
# describing the basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Functions in Data Science

In [ ]:
# obtaining the length of the dataframe  (number of columns)
len(df_exams)

1000

In [ ]:
# obtaining the highest index of the dataframe
max(df_exams.index)

999

In [ ]:
# obtaining the lowest index of the dataframe
min(df_exams.index)

0

In [ ]:
# obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [ ]:
# rounding the values of the dataset
round(df_exams, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# Selecting One Column from the dataframe
# Selecting one column

In [ ]:
# select a columnwith [] (preferred way to select a column)
df_exams['gender']
df_exams['test preparation course']

0           none
1      completed
2           none
3           none
4           none
5           none
6      completed
7           none
8      completed
9           none
10          none
11          none
12          none
13     completed
14          none
15          none
16          none
17          none
18     completed
19          none
20          none
21     completed
22          none
23          none
24     completed
25          none
26          none
27          none
28          none
29          none
30          none
31          none
32          none
33          none
34          none
35     completed
36          none
37          none
38     completed
39          none
40          none
41          none
42          none
43     completed
44          none
45          none
46     completed
47          none
48     completed
49     completed
50          none
51     completed
52          none
53          none
54     completed
55          none
56     completed
57          none
58     completed
59          none
60     completed
61          none
62          none
63          none
64          none
65          none
66          none
67          none
68          none
69          none
70     completed
71     completed
72          none
73          none
74          none
75          none
76          none
77     completed
78     completed
79          none
80          none
81          none
82     completed
83          none
84          none
85          none
86          none
87          none
88          none
89          none
90          none
91          none
92          none
93     completed
94          none
95     completed
96     completed
97     completed
98          none
99          none
100         none
101    completed
102         none
103    completed
104    completed
105         none
106         none
107    completed
108         none
109         none
110    completed
111         none
112         none
113         none
114    completed
115         none
116         none
117         none
118         none
119         none
120    completed
121    completed
122    completed
123         none
124         none
125         none
126         none
127    completed
128         none
129         none
130         none
131    completed
132    completed
133    completed
134    completed
135         none
136    completed
137         none
138         none
139    completed
140         none
141         none
142    completed
143         none
144         none
145         none
146         none
147         none
148    completed
149    completed
150    completed
151         none
152    completed
153         none
154         none
155    completed
156    completed
157         none
158    completed
159         none
160    completed
161    completed
162         none
163         none
164         none
165    completed
166    completed
167    completed
168    completed
169    completed
170    completed
171         none
172         none
173         none
174    completed
175    completed
176    completed
177    completed
178    completed
179    completed
180    completed
181         none
182         none
183         none
184    completed
185    completed
186         none
187    completed
188         none
189         none
190         none
191    completed
192         none
193    completed
194    completed
195         none
196    completed
197         none
198         none
199         none
200    completed
201         none
202         none
203         none
204         none
205    completed
206         none
207    completed
208         none
209         none
210    completed
211         none
212         none
213    completed
214    completed
215    completed
216    completed
217         none
218         none
219    completed
220    completed
221         none
222         none
223         none
224    completed
225         none
226         none
227         none
228         none
229    completed
230         none
231         none
232         none
233         none
234    completed
235         none
236         none
237    completed
238         none
239         none
240    completed
241         none
242         none
243         none
244         none
245         none
246         none
247    completed
248         none
249         none
250    completed
251         none
252    completed
253         none
254         none
255         none
256         none
257    completed
258         none
259    completed
260    completed
261    completed
262         none
263         none
264         none
265         none
266         none
267         none
268    completed
269         none
270         none
271         none
272         none
273         none
274    completed
275         none
276    completed
277    completed
278         none
279         none
280         none
281         none
282         none
283    completed
284         none
285    completed
286    completed
287         none
288         none
289    completed
290         none
291         none
292    completed
293         none
294    completed
295         none
296    completed
297    completed
298    completed
299         none
300    completed
301         none
302    completed
303         none
304    completed
305         none
306    completed
307         none
308         none
309         none
310         none
311         none
312    completed
313    completed
314    completed
315         none
316    completed
317         none
318         none
319         none
320    completed
321         none
322         none
323         none
324         none
325         none
326         none
327         none
328    completed
329         none
330         none
331         none
332    completed
333         none
334         none
335         none
336    completed
337         none
338         none
339    completed
340         none
341         none
342    completed
343    completed
344         none
345         none
346         none
347    completed
348         none
349         none
350         none
351         none
352    completed
353         none
354         none
355         none
356         none
357    completed
358         none
359         none
360         none
361    completed
362         none
363         none
364         none
365    completed
366    completed
367         none
368         none
369         none
370         none
371    completed
372         none
373    completed
374         none
375         none
376         none
377    completed
378         none
379         none
380         none
381    completed
382         none
383         none
384         none
385         none
386         none
387         none
388         none
389         none
390    completed
391         none
392         none
393    completed
394    completed
395         none
396         none
397         none
398         none
399         none
400    completed
401         none
402         none
403    completed
404         none
405         none
406    completed
407         none
408    completed
409    completed
410    completed
411    completed
412         none
413    completed
414    completed
415         none
416    completed
417         none
418         none
419    completed
420    completed
421    completed
422    completed
423    completed
424         none
425         none
426         none
427         none
428         none
429         none
430         none
431         none
432         none
433         none
434         none
435    completed
436         none
437         none
438         none
439    completed
440    completed
441         none
442         none
443         none
444         none
445    completed
446         none
447    completed
448         none
449         none
450    completed
451         none
452         none
453         none
454         none
455         none
456         none
457         none
458         none
459    completed
460         none
461         none
462         none
463         none
464    completed
465         none
466         none
467    completed
468    completed
469         none
470    completed
471         none
472    completed
473         none
474    completed
475    completed
476    completed
477         none
478         none
479         none
480    completed
481         none
482         none
483         none
484         none
485         none
486         none
487         none
488    completed
489    completed
490         none
491         none
492         none
493         none
494         none
495    completed
496         none
497    completed
498         none
499         none
500         none
501    completed
502         none
503    completed
504         none
505         none
506         none
507         none
508         none
509         none
510         none
511         none
512         none
513    completed
514    completed
515    completed
516         none
517    completed
518    completed
519    completed
520         none
521         none
522         none
523         none
524    completed
525         none
526    completed
527         none
528         none
529         none
530    completed
531         none
532    completed
533    completed
534    completed
535    completed
536    completed
537         none
538    completed
539    completed
540    completed
541    completed
542         none
543         none
544         none
545    completed
546    completed
547    completed
548         none
549         none
550         none
551    completed
552         none
553         none
554         none
555         none
556    completed
557         none
558         none
559         none
560    completed
561         none
562    completed
563    completed
564         none
565         none
566    completed
567    completed
568         none
569         none
570    completed
571         none
572         none
573    completed
574         none
575    completed
576    completed
577         none
578    completed
579         none
580         none
581         none
582         none
583    completed
584         none
585         none
586         none
587         none
588         none
589         none
590         none
591         none
592         none
593         none
594    completed
595    completed
596         none
597         none
598         none
599         none
600         none
601         none
602         none
603         none
604    completed
605         none
606         none
607         none
608         none
609         none
610    completed
611         none
612    completed
613         none
614         none
615         none
616         none
617         none
618         none
619    completed
620         none
621         none
622    completed
623    completed
624         none
625    completed
626    completed
627         none
628         none
629    completed
630         none
631         none
632    completed
633         none
634         none
635         none
636    completed
637    completed
638         none
639         none
640         none
641    completed
642         none
643    completed
644         none
645    completed
646         none
647         none
648         none
649    completed
650    completed
651    completed
652    completed
653    completed
654         none
655         none
656         none
657         none
658         none
659         none
660         none
661         none
662         none
663         none
664         none
665    completed
666    completed
667         none
668         none
669    completed
670         none
671         none
672         none
673    completed
674    completed
675    completed
676    completed
677    completed
678         none
679         none
680         none
681         none
682         none
683    completed
684    completed
685    completed
686    completed
687         none
688         none
689         none
690         none
691         none
692    completed
693         none
694         none
695         none
696    completed
697         none
698    completed
699         none
700    completed
701         none
702    completed
703         none
704    completed
705         none
706         none
707         none
708         none
709    completed
710    completed
711    completed
712         none
713         none
714    completed
715    completed
716    completed
717    completed
718         none
719    completed
720         none
721    completed
722    completed
723         none
724         none
725    completed
726    completed
727    completed
728         none
729         none
730    completed
731         none
732    completed
733         none
734         none
735         none
736         none
737    completed
738         none
739         none
740         none
741         none
742         none
743    completed
744         none
745         none
746         none
747         none
748         none
749    completed
750    completed
751         none
752    completed
753    completed
754         none
755         none
756         none
757    completed
758    completed
759    completed
760         none
761         none
762    completed
763         none
764         none
765         none
766    completed
767    completed
768         none
769         none
770         none
771         none
772    completed
773         none
774         none
775         none
776         none
777         none
778    completed
779    completed
780         none
781         none
782    completed
783    completed
784    completed
785    completed
786         none
787         none
788         none
789         none
790         none
791         none
792         none
793    completed
794         none
795    completed
796         none
797         none
798         none
799         none
800    completed
801    completed
802         none
803         none
804         none
805         none
806         none
807         none
808         none
809         none
810         none
811         none
812    completed
813    completed
814         none
815    completed
816         none
817    completed
818         none
819         none
820    completed
821         none
822    completed
823         none
824         none
825         none
826    completed
827         none
828    completed
829         none
830         none
831    completed
832         none
833    completed
834         none
835    completed
836         none
837    completed
838    completed
839         none
840         none
841         none
842    completed
843    completed
844    completed
845         none
846    completed
847         none
848         none
849         none
850         none
851         none
852         none
853         none
854         none
855         none
856         none
857         none
858    completed
859         none
860         none
861         none
862    completed
863    completed
864         none
865    completed
866         none
867         none
868    completed
869         none
870         none
871    completed
872    completed
873         none
874         none
875         none
876         none
877         none
878         none
879         none
880    completed
881    completed
882         none
883         none
884         none
885    completed
886    completed
887         none
888         none
889         none
890    completed
891         none
892         none
893    completed
894         none
895         none
896         none
897    completed
898    completed
899    completed
900         none
901         none
902    completed
903    completed
904         none
905         none
906         none
907    completed
908         none
909    completed
910         none
911         none
912    completed
913    completed
914         none
915         none
916    completed
917         none
918    completed
919    completed
920         none
921         none
922         none
923         none
924         none
925    completed
926         none
927    completed
928    completed
929         none
930    completed
931         none
932    completed
933    completed
934    completed
935         none
936         none
937         none
938    completed
939    completed
940    completed
941         none
942         none
943    completed
944         none
945         none
946         none
947         none
948    completed
949    completed
950         none
951    completed
952         none
953    completed
954         none
955         none
956         none
957         none
958         none
959         none
960         none
961         none
962         none
963    completed
964         none
965         none
966    completed
967         none
968         none
969         none
970         none
971    completed
972    completed
973         none
974         none
975    completed
976    completed
977         none
978    completed
979         none
980         none
981         none
982    completed
983    completed
984         none
985         none
986         none
987    completed
988         none
989    completed
990    completed
991    completed
992         none
993         none
994         none
995    completed
996         none
997    completed
998    completed
999         none
Name: test preparation course, dtype: object

In [ ]:
# check out the data type of a column
type(df_exams['gender'])

pandas.core.series.Series

In [ ]:
# series: atrributes and methods
df_exams['gender'].index
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

# selecting 2 or more columns

In [ ]:
# select 2 columns using [[]]
df_exams[['gender', 'lunch']]

     gender         lunch
0    female      standard
1    female      standard
2    female      standard
3      male  free/reduced
4      male      standard
5    female      standard
6    female      standard
7      male  free/reduced
8      male  free/reduced
9    female  free/reduced
10     male      standard
11     male      standard
12   female      standard
13     male      standard
14   female      standard
15   female      standard
16     male      standard
17   female  free/reduced
18     male  free/reduced
19   female  free/reduced
20     male      standard
21   female  free/reduced
22     male      standard
23   female      standard
24     male  free/reduced
25     male  free/reduced
26     male      standard
27   female      standard
28     male      standard
29   female      standard
30   female      standard
31   female      standard
32   female  free/reduced
33     male      standard
34     male      standard
35     male      standard
36   female      standard
37   female  free/reduced
38   female  free/reduced
39     male  free/reduced
40     male  free/reduced
41   female      standard
42   female      standard
43     male  free/reduced
44   female  free/reduced
45     male      standard
46   female      standard
47   female      standard
48   female  free/reduced
49     male      standard
50     male      standard
51     male  free/reduced
52     male      standard
53     male      standard
54   female  free/reduced
55   female  free/reduced
56   female      standard
57     male      standard
58     male      standard
59   female  free/reduced
60     male  free/reduced
61     male  free/reduced
62     male  free/reduced
63   female      standard
64   female      standard
65     male      standard
66     male  free/reduced
67   female      standard
68     male  free/reduced
69   female      standard
70   female  free/reduced
71     male      standard
72   female  free/reduced
73     male  free/reduced
74     male      standard
75     male  free/reduced
76     male      standard
77     male      standard
78   female      standard
79   female      standard
80   female      standard
81     male  free/reduced
82     male  free/reduced
83     male      standard
84     male  free/reduced
85   female      standard
86   female  free/reduced
87   female      standard
88   female      standard
89   female      standard
90   female      standard
91     male  free/reduced
92     male      standard
93     male  free/reduced
94   female      standard
95     male  free/reduced
96     male      standard
97   female      standard
98   female  free/reduced
99   female      standard
100    male      standard
101    male      standard
102  female      standard
103    male      standard
104    male      standard
105  female      standard
106  female      standard
107    male      standard
108  female  free/reduced
109  female      standard
110  female  free/reduced
111    male      standard
112    male      standard
113  female      standard
114  female      standard
115    male      standard
116  female  free/reduced
117  female      standard
118  female      standard
119  female      standard
120  female      standard
121    male      standard
122  female      standard
123    male  free/reduced
124    male      standard
125  female      standard
126    male      standard
127    male      standard
128    male      standard
129  female      standard
130    male      standard
131    male  free/reduced
132    male  free/reduced
133  female      standard
134    male  free/reduced
135    male      standard
136    male      standard
137    male      standard
138  female      standard
139    male      standard
140  female      standard
141  female  free/reduced
142  female  free/reduced
143    male      standard
144    male      standard
145  female  free/reduced
146    male      standard
147    male  free/reduced
148  female      standard
149    male  free/reduced
150    male      standard
151    male      standard
152  female      standard
153    male      standard
154    male      standard
155  female      standard
156  female  free/reduced
157    male  free/reduced
158  female      standard
159    male  free/reduced
160    male  free/reduced
161  female  free/reduced
162    male  free/reduced
163    male      standard
164  female      standard
165  female      standard
166    male  free/reduced
167  female  free/reduced
168  female      standard
169  female  free/reduced
170    male      standard
171    male      standard
172  female      standard
173  female      standard
174  female  free/reduced
175  female      standard
176  female  free/reduced
177  female      standard
178  female  free/reduced
179  female      standard
180    male  free/reduced
181  female  free/reduced
182  female      standard
183  female      standard
184    male  free/reduced
185    male  free/reduced
186    male      standard
187    male      standard
188    male  free/reduced
189  female      standard
190  female      standard
191    male      standard
192  female      standard
193    male      standard
194  female      standard
195    male      standard
196    male  free/reduced
197    male  free/reduced
198  female  free/reduced
199  female  free/reduced
200  female      standard
201  female  free/reduced
202    male      standard
203  female      standard
204    male      standard
205    male      standard
206    male      standard
207    male      standard
208  female  free/reduced
209  female  free/reduced
210    male  free/reduced
211    male  free/reduced
212  female  free/reduced
213    male  free/reduced
214    male      standard
215    male      standard
216  female  free/reduced
217  female  free/reduced
218    male  free/reduced
219    male      standard
220  female      standard
221    male      standard
222  female  free/reduced
223    male      standard
224  female      standard
225  female  free/reduced
226  female      standard
227    male      standard
228    male  free/reduced
229  female      standard
230    male      standard
231    male      standard
232  female      standard
233    male      standard
234    male      standard
235    male      standard
236    male  free/reduced
237  female      standard
238    male      standard
239    male      standard
240    male  free/reduced
241  female      standard
242  female      standard
243    male      standard
244    male      standard
245    male      standard
246    male      standard
247  female      standard
248  female      standard
249    male      standard
250    male      standard
251  female  free/reduced
252  female      standard
253    male      standard
254    male      standard
255  female      standard
256  female  free/reduced
257    male      standard
258  female      standard
259  female  free/reduced
260  female  free/reduced
261    male      standard
262  female  free/reduced
263  female      standard
264    male      standard
265    male  free/reduced
266  female      standard
267  female      standard
268  female      standard
269  female  free/reduced
270    male      standard
271    male      standard
272  female  free/reduced
273  female      standard
274    male      standard
275    male      standard
276  female      standard
277  female      standard
278  female  free/reduced
279    male  free/reduced
280    male      standard
281    male      standard
282  female  free/reduced
283  female  free/reduced
284  female      standard
285    male      standard
286    male      standard
287  female      standard
288    male  free/reduced
289    male      standard
290    male      standard
291    male      standard
292    male      standard
293  female      standard
294    male  free/reduced
295    male  free/reduced
296    male      standard
297    male      standard
298    male  free/reduced
299    male  free/reduced
300    male  free/reduced
301    male  free/reduced
302  female      standard
303    male      standard
304  female      standard
305    male      standard
306    male      standard
307    male      standard
308  female  free/reduced
309  female  free/reduced
310  female      standard
311    male      standard
312    male      standard
313  female  free/reduced
314  female      standard
315    male      standard
316  female      standard
317    male      standard
318    male      standard
319  female  free/reduced
320  female  free/reduced
321  female      standard
322  female      standard
323  female  free/reduced
324  female  free/reduced
325  female      standard
326    male      standard
327    male  free/reduced
328    male      standard
329  female      standard
330    male      standard
331    male      standard
332    male      standard
333    male      standard
334  female      standard
335  female  free/reduced
336    male      standard
337    male      standard
338  female  free/reduced
339  female  free/reduced
340    male  free/reduced
341  female      standard
342  female      standard
343    male      standard
344    male      standard
345  female      standard
346    male      standard
347  female      standard
348    male  free/reduced
349    male      standard
350  female      standard
351    male      standard
352  female      standard
353  female      standard
354  female      standard
355  female      standard
356    male      standard
357  female  free/reduced
358    male  free/reduced
359  female      standard
360  female      standard
361    male      standard
362  female      standard
363  female  free/reduced
364    male      standard
365    male  free/reduced
366    male      standard
367    male  free/reduced
368  female  free/reduced
369  female      standard
370    male      standard
371  female  free/reduced
372    male      standard
373  female      standard
374  female      standard
375    male  free/reduced
376  female      standard
377  female  free/reduced
378  female      standard
379    male      standard
380  female      standard
381    male      standard
382    male  free/reduced
383  female  free/reduced
384  female  free/reduced
385  female      standard
386  female      standard
387  female  free/reduced
388  female      standard
389    male      standard
390    male  free/reduced
391  female      standard
392    male      standard
393    male      standard
394  female      standard
395    male  free/reduced
396  female  free/reduced
397  female      standard
398    male      standard
399    male      standard
400  female      standard
401    male      standard
402  female  free/reduced
403  female      standard
404  female      standard
405  female      standard
406    male      standard
407  female      standard
408  female  free/reduced
409    male      standard
410  female      standard
411    male      standard
412    male      standard
413    male      standard
414  female  free/reduced
415    male      standard
416    male      standard
417    male      standard
418    male      standard
419    male  free/reduced
420  female  free/reduced
421  female      standard
422  female  free/reduced
423  female      standard
424    male  free/reduced
425  female  free/reduced
426    male      standard
427    male  free/reduced
428    male  free/reduced
429    male  free/reduced
430    male  free/reduced
431  female      standard
432    male      standard
433  female  free/reduced
434    male      standard
435    male  free/reduced
436    male      standard
437    male  free/reduced
438    male      standard
439    male      standard
440  female      standard
441  female      standard
442  female  free/reduced
443  female      standard
444    male  free/reduced
445  female      standard
446    male  free/reduced
447    male      standard
448    male      standard
449    male      standard
450  female  free/reduced
451  female      standard
452  female  free/reduced
453    male  free/reduced
454  female  free/reduced
455    male  free/reduced
456  female      standard
457    male  free/reduced
458  female      standard
459    male      standard
460    male  free/reduced
461    male  free/reduced
462  female      standard
463  female  free/reduced
464    male      standard
465  female      standard
466  female  free/reduced
467    male  free/reduced
468  female  free/reduced
469    male      standard
470  female      standard
471  female      standard
472  female      standard
473  female      standard
474  female      standard
475  female      standard
476    male      standard
477    male      standard
478  female      standard
479    male      standard
480    male      standard
481  female  free/reduced
482    male  free/reduced
483    male      standard
484  female      standard
485    male      standard
486    male  free/reduced
487  female  free/reduced
488    male      standard
489    male  free/reduced
490  female  free/reduced
491  female      standard
492  female      standard
493  female      standard
494  female      standard
495    male      standard
496  female      standard
497  female  free/reduced
498  female      standard
499    male      standard
500  female      standard
501  female      standard
502    male  free/reduced
503  female      standard
504  female  free/reduced
505  female      standard
506    male      standard
507    male  free/reduced
508    male      standard
509  female      standard
510    male      standard
511    male      standard
512    male  free/reduced
513  female      standard
514  female  free/reduced
515  female      standard
516  female      standard
517  female      standard
518  female      standard
519  female  free/reduced
520    male      standard
521  female      standard
522    male      standard
523    male  free/reduced
524    male      standard
525    male      standard
526    male  free/reduced
527  female  free/reduced
528  female  free/reduced
529  female      standard
530  female      standard
531  female      standard
532    male      standard
533  female      standard
534    male      standard
535  female  free/reduced
536    male      standard
537  female      standard
538    male      standard
539    male      standard
540    male      standard
541    male  free/reduced
542  female      standard
543  female      standard
544  female      standard
545    male  free/reduced
546  female      standard
547    male      standard
548  female  free/reduced
549    male      standard
550    male  free/reduced
551    male  free/reduced
552  female      standard
553    male  free/reduced
554    male      standard
555  female  free/reduced
556  female      standard
557    male  free/reduced
558  female  free/reduced
559    male      standard
560  female      standard
561  female      standard
562    male      standard
563  female  free/reduced
564    male  free/reduced
565    male      standard
566  female  free/reduced
567  female  free/reduced
568    male  free/reduced
569    male  free/reduced
570    male      standard
571    male      standard
572  female      standard
573  female  free/reduced
574  female      standard
575    male  free/reduced
576    male      standard
577  female      standard
578  female  free/reduced
579  female      standard
580  female      standard
581  female      standard
582  female  free/reduced
583  female      standard
584  female      standard
585  female      standard
586  female      standard
587  female  free/reduced
588  female      standard
589  female      standard
590    male  free/reduced
591    male      standard
592    male      standard
593  female      standard
594  female      standard
595  female      standard
596    male  free/reduced
597    male      standard
598  female      standard
599  female      standard
600  female      standard
601  female      standard
602  female      standard
603    male  free/reduced
604    male  free/reduced
605    male      standard
606  female      standard
607  female  free/reduced
608  female      standard
609  female      standard
610    male  free/reduced
611  female      standard
612    male      standard
613  female      standard
614  female      standard
615  female      standard
616  female      standard
617    male      standard
618    male      standard
619    male  free/reduced
620  female  free/reduced
621    male  free/reduced
622    male  free/reduced
623    male      standard
624  female  free/reduced
625    male      standard
626    male  free/reduced
627    male      standard
628    male  free/reduced
629  female      standard
630    male      standard
631    male      standard
632  female      standard
633  female      standard
634    male      standard
635    male      standard
636  female  free/reduced
637  female      standard
638    male      standard
639  female      standard
640    male      standard
641  female  free/reduced
642  female  free/reduced
643  female      standard
644    male      standard
645  female      standard
646  female      standard
647  female  free/reduced
648  female      standard
649  female      standard
650    male  free/reduced
651  female      standard
652  female      standard
653  female      standard
654  female      standard
655  female      standard
656    male  free/reduced
657    male      standard
658  female  free/reduced
659    male      standard
660    male  free/reduced
661    male      standard
662  female  free/reduced
663  female      standard
664    male      standard
665  female  free/reduced
666  female  free/reduced
667  female  free/reduced
668    male      standard
669    male      standard
670  female  free/reduced
671    male  free/reduced
672  female      standard
673  female      standard
674  female      standard
675  female      standard
676  female      standard
677  female      standard
678    male  free/reduced
679    male  free/reduced
680  female      standard
681    male      standard
682    male      standard
683  female  free/reduced
684    male      standard
685  female      standard
686    male      standard
687    male  free/reduced
688    male  free/reduced
689    male  free/reduced
690  female      standard
691  female  free/reduced
692  female  free/reduced
693  female      standard
694  female      standard
695  female  free/reduced
696  female      standard
697  female      standard
698  female      standard
699    male  free/reduced
700  female      standard
701  female      standard
702    male      standard
703  female      standard
704  female  free/reduced
705    male  free/reduced
706    male      standard
707    male      standard
708    male      standard
709  female  free/reduced
710    male      standard
711  female      standard
712  female      standard
713    male      standard
714  female      standard
715  female  free/reduced
716    male      standard
717  female      standard
718  female      standard
719    male  free/reduced
720  female  free/reduced
721    male  free/reduced
722  female  free/reduced
723    male      standard
724    male      standard
725    male      standard
726  female      standard
727    male      standard
728  female  free/reduced
729    male      standard
730  female  free/reduced
731    male  free/reduced
732  female      standard
733    male      standard
734  female  free/reduced
735    male      standard
736    male      standard
737  female  free/reduced
738    male      standard
739    male  free/reduced
740    male      standard
741  female  free/reduced
742  female      standard
743  female      standard
744    male  free/reduced
745    male      standard
746    male      standard
747    male      standard
748  female  free/reduced
749    male      standard
750    male      standard
751    male      standard
752    male  free/reduced
753  female      standard
754    male  free/reduced
755  female      standard
756    male      standard
757    male  free/reduced
758  female  free/reduced
759    male      standard
760  female  free/reduced
761  female      standard
762    male      standard
763  female      standard
764    male      standard
765  female      standard
766  female      standard
767    male      standard

In [ ]:
# checkout the data type of this selection
type(df_exams[['gender', 'lunch']]) # this result brings the data type known as a dataframe

pandas.core.frame.DataFrame

In [ ]:
# checkout the data type of this selection
type(df_exams['gender']) # the type of data type here is a Series. This is because there is only one square bracket

pandas.core.series.Series

In [ ]:
# select 2 or more columns using [[]]
df_exams[['gender', 'lunch', 'reading score', 'writing score']]

     gender         lunch  reading score  writing score
0    female      standard             72             74
1    female      standard             90             88
2    female      standard             95             93
3      male  free/reduced             57             44
4      male      standard             78             75
5    female      standard             83             78
6    female      standard             95             92
7      male  free/reduced             43             39
8      male  free/reduced             64             67
9    female  free/reduced             60             50
10     male      standard             54             52
11     male      standard             52             43
12   female      standard             81             73
13     male      standard             72             70
14   female      standard             53             58
15   female      standard             75             78
16     male      standard             89             86
17   female  free/reduced             32             28
18     male  free/reduced             42             46
19   female  free/reduced             58             61
20     male      standard             69             63
21   female  free/reduced             75             70
22     male      standard             54             53
23   female      standard             73             73
24     male  free/reduced             71             80
25     male  free/reduced             74             72
26     male      standard             54             55
27   female      standard             69             75
28     male      standard             70             65
29   female      standard             70             75
30   female      standard             74             74
31   female      standard             65             61
32   female  free/reduced             72             65
33     male      standard             42             38
34     male      standard             87             82
35     male      standard             81             79
36   female      standard             81             83
37   female  free/reduced             64             59
38   female  free/reduced             90             88
39     male  free/reduced             56             57
40     male  free/reduced             61             54
41   female      standard             73             68
42   female      standard             58             65
43     male  free/reduced             65             66
44   female  free/reduced             56             54
45     male      standard             54             57
46   female      standard             65             62
47   female      standard             71             76
48   female  free/reduced             74             76
49     male      standard             84             82
50     male      standard             55             48
51     male  free/reduced             69             68
52     male      standard             44             42
53     male      standard             78             75
54   female  free/reduced             84             87
55   female  free/reduced             41             43
56   female      standard             85             86
57     male      standard             55             49
58     male      standard             59             58
59   female  free/reduced             17             10
60     male  free/reduced             74             72
61     male  free/reduced             39             34
62     male  free/reduced             61             55
63   female      standard             80             71
64   female      standard             58             59
65     male      standard             64             61
66     male  free/reduced             37             37
67   female      standard             72             74
68     male  free/reduced             58             56
69   female      standard             64             57
70   female  free/reduced             63             73
71     male      standard             55             63
72   female  free/reduced             51             48
73     male  free/reduced             57             56
74     male      standard             49             41
75     male  free/reduced             41             38
76     male      standard             26             22
77     male      standard             78             81
78   female      standard             74             72
79   female      standard             68             68
80   female      standard             49             50
81     male  free/reduced             45             45
82     male  free/reduced             47             54
83     male      standard             64             63
84     male  free/reduced             39             34
85   female      standard             80             82
86   female  free/reduced             83             88
87   female      standard             71             74
88   female      standard             70             67
89   female      standard             86             82
90   female      standard             72             74
91     male  free/reduced             34             36
92     male      standard             79             71
93     male  free/reduced             45             50
94   female      standard             86             92
95     male  free/reduced             81             82
96     male      standard             66             62
97   female      standard             72             70
98   female  free/reduced             67             62
99   female      standard             67             62
100    male      standard             67             67
101    male      standard             74             74
102  female      standard             91             89
103    male      standard             44             47
104    male      standard             86             90
105  female      standard             67             72
106  female      standard            100            100
107    male      standard             63             64
108  female  free/reduced             76             70
109  female      standard             64             72
110  female  free/reduced             89             98
111    male      standard             55             49
112    male      standard             53             47
113  female      standard             58             54
114  female      standard            100            100
115    male      standard             77             74
116  female  free/reduced             85             82
117  female      standard             82             79
118  female      standard             63             61
119  female      standard             69             65
120  female      standard             92             89
121    male      standard             89             92
122  female      standard             93             93
123    male  free/reduced             57             56
124    male      standard             80             73
125  female      standard             95             86
126    male      standard             68             67
127    male      standard             77             74
128    male      standard             82             74
129  female      standard             49             51
130    male      standard             84             82
131    male  free/reduced             37             40
132    male  free/reduced             74             70
133  female      standard             81             84
134    male  free/reduced             79             75
135    male      standard             55             48
136    male      standard             54             41
137    male      standard             55             56
138  female      standard             66             67
139    male      standard             61             69
140  female      standard             72             71
141  female  free/reduced             62             64
142  female  free/reduced             55             54
143    male      standard             43             47
144    male      standard             73             78
145  female  free/reduced             39             33
146    male      standard             84             75
147    male  free/reduced             68             66
148  female      standard             75             81
149    male  free/reduced            100             93
150    male      standard             67             69
151    male      standard             67             68
152  female      standard             70             66
153    male      standard             49             47
154    male      standard             67             61
155  female      standard             89             88
156  female  free/reduced             74             78
157    male  free/reduced             60             60
158  female      standard             86             87
159    male  free/reduced             62             64
160    male  free/reduced             78             74
161  female  free/reduced             88             85
162    male  free/reduced             53             52
163    male      standard             53             49
164  female      standard             92             91
165  female      standard            100            100
166    male  free/reduced             51             51
167  female  free/reduced             76             78
168  female      standard             83             78
169  female  free/reduced             75             70
170    male      standard             73             74
171    male      standard             88             78
172  female      standard             86             81
173  female      standard             67             70
174  female  free/reduced             51             54
175  female      standard             91             87
176  female  free/reduced             54             58
177  female      standard             77             77
178  female  free/reduced             70             62
179  female      standard            100            100
180    male  free/reduced             68             75
181  female  free/reduced             64             66
182  female      standard             50             47
183  female      standard             69             70
184    male  free/reduced             52             49
185    male  free/reduced             67             65
186    male      standard             76             65
187    male      standard             66             68
188    male  free/reduced             52             45
189  female      standard             88             87
190  female      standard             65             69
191    male      standard             83             79
192  female      standard             64             66
193    male      standard             62             62
194  female      standard             84             85
195    male      standard             55             52
196    male  free/reduced             69             65
197    male  free/reduced             56             51
198  female  free/reduced             53             55
199  female  free/reduced             79             76
200  female      standard             84             86
201  female  free/reduced             81             77
202    male      standard             77             69
203  female      standard             69             68
204    male      standard             41             42
205    male      standard             71             78
206    male      standard             62             62
207    male      standard             80             76
208  female  free/reduced             81             76
209  female  free/reduced             61             66
210    male  free/reduced             79             79
211    male  free/reduced             28             27
212  female  free/reduced             62             60
213    male  free/reduced             51             56
214    male      standard             91             81
215    male      standard             83             75
216  female  free/reduced             86             88
217  female  free/reduced             42             39
218    male  free/reduced             77             70
219    male      standard             56             56
220  female      standard             68             74
221    male      standard             85             73
222  female  free/reduced             65             62
223    male      standard             80             75
224  female      standard             66             73
225  female  free/reduced             56             54
226  female      standard             72             71
227    male      standard             50             54
228    male  free/reduced             72             64
229  female      standard             95             94
230    male      standard             64             66
231    male      standard             43             42
232  female      standard             86             83
233    male      standard             87             78
234    male      standard             82             84
235    male      standard             75             77
236    male  free/reduced             66             67
237  female      standard             60             74
238    male      standard             52             51
239    male      standard             80             80
240    male  free/reduced             68             66
241  female      standard             83             83
242  female      standard             52             55
243    male      standard             51             43
244    male      standard             74             69
245    male      standard             76             71
246    male      standard             76             74
247  female      standard             70             68
248  female      standard             64             62
249    male      standard             60             53
250    male      standard             49             49
251  female  free/reduced             83             83
252  female      standard             70             70
253    male      standard             80             72
254    male      standard             52             52
255  female      standard             73             70
256  female  free/reduced             73             68
257    male      standard             77             77
258  female      standard             75             78
259  female  free/reduced             81             81
260  female  free/reduced             79             77
261    male      standard             79             78
262  female  free/reduced             50             51
263  female      standard             93             90
264    male      standard             73             68
265    male  free/reduced             42             41
266  female      standard             75             81
267  female      standard             72             77
268  female      standard             92             95
269  female  free/reduced             76             70
270    male      standard             63             61
271    male      standard             49             42
272  female  free/reduced             53             58
273  female      standard             70             71
274    male      standard             85             76
275    male      standard             78             73
276  female      standard             92             93
277  female      standard             63             75
278  female  free/reduced             86             80
279    male  free/reduced             56             57
280    male      standard             52             42
281    male      standard             48             46
282  female  free/reduced             79             84
283  female  free/reduced             78             78
284  female      standard             46             46
285    male      standard             82             82
286    male      standard             82             88
287  female      standard             89             82
288    male  free/reduced             75             76
289    male      standard             76             77
290    male      standard             70             68
291    male      standard             73             70
292    male      standard             60             57
293  female      standard             73             75
294    male  free/reduced             77             80
295    male  free/reduced             62             60
296    male      standard             41             43
297    male      standard             74             68
298    male  free/reduced             46             50
299    male  free/reduced             87             75
300    male  free/reduced             78             81
301    male  free/reduced             54             52
302  female      standard             84             81
303    male      standard             76             64
304  female      standard             75             83
305    male      standard             67             69
306    male      standard             87             81
307    male      standard             52             44
308  female  free/reduced             71             67
309  female  free/reduced             57             52
310  female      standard             76             80
311    male      standard             60             57
312    male      standard             61             68
313  female  free/reduced             67             69
314  female      standard             64             75
315    male      standard             66             65
316  female      standard             82             91
317    male      standard             72             78
318    male      standard             71             69
319  female  free/reduced             65             63
320  female  free/reduced             79             84
321  female      standard             86             79
322  female      standard             81             80
323  female  free/reduced             53             53
324  female  free/reduced             46             43
325  female      standard             90             94
326    male      standard             61             62
327    male  free/reduced             23             19
328    male      standard             75             77
329  female      standard             55             51
330    male      standard             60             61
331    male      standard             37             35
332    male      standard             56             53
333    male      standard             78             81
334  female      standard             93             95
335  female  free/reduced             68             66
336    male      standard             70             69
337    male      standard             51             43
338  female  free/reduced             38             27
339  female  free/reduced             55             60
340    male  free/reduced             61             52
341  female      standard             73             63
342  female      standard             76             74
343    male      standard             72             67
344    male      standard             73             67
345  female      standard             80             75
346    male      standard             61             57
347  female      standard             94             95
348    male  free/reduced             74             66
349    male      standard             74             76
350  female      standard             65             69
351    male      standard             57             52
352  female      standard             78             80
353  female      standard             58             57
354  female      standard             71             70
355  female      standard             72             70

# Adding a new column with a scalar score

In [ ]:
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
5,female,group B,associate's degree,standard,none,71,83,78,70
6,female,group B,some college,standard,completed,88,95,92,70
7,male,group B,some college,free/reduced,none,40,43,39,70
8,male,group D,high school,free/reduced,completed,64,64,67,70
9,female,group B,high school,free/reduced,none,38,60,50,70
10,male,group C,associate's degree,standard,none,58,54,52,70
11,male,group D,associate's degree,standard,none,40,52,43,70
12,female,group B,high school,standard,none,65,81,73,70
13,male,group A,some college,standard,completed,78,72,70,70
14,female,group A,master's degree,standard,none,50,53,58,70
15,female,group C,some high school,standard,none,69,75,78,70
16,male,group C,high school,standard,none,88,89,86,70
17,female,group B,some high school,free/reduced,none,18,32,28,70
18,male,group C,master's degree,free/reduced,completed,46,42,46,70
19,female,group C,associate's degree,free/reduced,none,54,58,61,70
20,male,group D,high school,standard,none,66,69,63,70
21,female,group B,some college,free/reduced,completed,65,75,70,70
22,male,group D,some college,standard,none,44,54,53,70
23,female,group C,some high school,standard,none,69,73,73,70
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,70
25,male,group A,master's degree,free/reduced,none,73,74,72,70
26,male,group B,some college,standard,none,69,54,55,70
27,female,group C,bachelor's degree,standard,none,67,69,75,70
28,male,group C,high school,standard,none,70,70,65,70
29,female,group D,master's degree,standard,none,62,70,75,70
30,female,group D,some college,standard,none,69,74,74,70
31,female,group B,some college,standard,none,63,65,61,70
32,female,group E,master's degree,free/reduced,none,56,72,65,70
33,male,group D,some college,standard,none,40,42,38,70
34,male,group E,some college,standard,none,97,87,82,70
35,male,group E,associate's degree,standard,completed,81,81,79,70
36,female,group D,associate's degree,standard,none,74,81,83,70
37,female,group D,some high school,free/reduced,none,50,64,59,70
38,female,group D,associate's degree,free/reduced,completed,75,90,88,70
39,male,group B,associate's degree,free/reduced,none,57,56,57,70
40,male,group C,associate's degree,free/reduced,none,55,61,54,70
41,female,group C,associate's degree,standard,none,58,73,68,70
42,female,group B,associate's degree,standard,none,53,58,65,70
43,male,group B,some college,free/reduced,completed,59,65,66,70
44,female,group E,associate's degree,free/reduced,none,50,56,54,70
45,male,group B,associate's degree,standard,none,65,54,57,70
46,female,group A,associate's degree,standard,completed,55,65,62,70
47,female,group C,high school,standard,none,66,71,76,70
48,female,group D,associate's degree,free/reduced,completed,57,74,76,70
49,male,group C,high school,standard,completed,82,84,82,70
50,male,group E,some college,standard,none,53,55,48,70
51,male,group E,associate's degree,free/reduced,completed,77,69,68,70
52,male,group C,some college,standard,none,53,44,42,70
53,male,group D,high school,standard,none,88,78,75,70
54,female,group C,some high school,free/reduced,completed,71,84,87,70
55,female,group C,high school,free/reduced,none,33,41,43,70
56,female,group E,associate's degree,standard,completed,82,85,86,70
57,male,group D,associate's degree,standard,none,52,55,49,70
58,male,group D,some college,standard,completed,58,59,58,70
59,female,group C,some high school,free/reduced,none,0,17,10,70
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,70
61,male,group A,some high school,free/reduced,none,39,39,34,70
62,male,group A,associate's degree,free/reduced,none,62,61,55,70
63,female,group C,associate's degree,standard,none,69,80,71,70
64,female,group D,some high school,standard,none,59,58,59,70
65,male,group B,some high school,standard,none,67,64,61,70
66,male,group D,some high school,free/reduced,none,45,37,37,70
67,female,group C,some college,standard,none,60,72,74,70
68,male,group B,associate's degree,free/reduced,none,61,58,56,70
69,female,group C,associate's degree,standard,none,39,64,57,70
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,70
72,female,group A,associate's degree,free/reduced,none,41,51,48,70
73,male,group C,some high school,free/reduced,none,61,57,56,70
74,male,group C,some high school,standard,none,49,49,41,70
75,male,group B,associate's degree,free/reduced,none,44,41,38,70
76,male,group E,some high school,standard,none,30,26,22,70
77,male,group A,bachelor's degree,standard,completed,80,78,81,70
78,female,group D,some high school,standard,completed,61,74,72,70
79,female,group E,master's degree,standard,none,62,68,68,70
80,female,group B,associate's degree,standard,none,47,49,50,70
81,male,group B,high school,free/reduced,none,49,45,45,70
82,male,group A,some college,free/reduced,completed,50,47,54,70
83,male,group E,associate's degree,standard,none,72,64,63,70
84,male,group D,high school,free/reduced,none,42,39,34,70
85,female,group C,some college,standard,none,73,80,82,70
86,female,group C,some college,free/reduced,none,76,83,88,70
87,female,group D,associate's degree,standard,none,71,71,74,70
88,female,group A,some college,standard,none,58,70,67,70
89,female,group D,some high school,standard,none,73,86,82,70
90,female,group C,bachelor's degree,standard,none,65,72,74,70
91,male,group C,high school,free/reduced,none,27,34,36,70
92,male,group C,high school,standard,none,71,79,71,70
93,male,group C,associate's degree,free/reduced,completed,43,45,50,70
94,female,group B,some college,standard,none,79,86,92,70
95,male,group C,associate's degree,free/reduced,completed,78,81,82,70
96,male,group B,some high school,standard,completed,65,66,62,70
97,female,group E,some college,standard,completed,63,72,70,70
98,female,group D,some college,free/reduced,none,58,67,62,70
99,female,group D,bachelor's degree,standard,none,65,67,62,70
100,male,group B,some college,standard,none,79,67,67,70
101,male,group D,bachelor's degree,standard,completed,68,74,74,70
102,female,group D,associate's degree,standard,none,85,91,89,70
103,male,group B,high school,standard,completed,60,44,47,70
104,male,group C,some college,standard,completed,98,86,90,70
105,female,group C,some college,standard,none,58,67,72,70
106,female,group D,master's degree,standard,none,87,100,100,70
107,male,group E,associate's degree,standard,completed,66,63,64,70
108,female,group B,associate's degree,free/reduced,none,52,76,70,70
109,female,group B,some high school,standard,none,70,64,72,70
110,female,group D,associate's degree,free/reduced,completed,77,89,98,70
111,male,group C,high school,standard,none,62,55,49,70
112,male,group A,associate's degree,standard,none,54,53,47,70
113,female,group D,some college,standard,none,51,58,54,70
114,female,group E,bachelor's degree,standard,completed,99,100,100,70
115,male,group C,high school,standard,none,84,77,74,70
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,70
117,female,group D,bachelor's degree,standard,none,78,82,79,70
118,female,group D,some high school,standard,none,51,63,61,70
119,female,group C,some college,standard,none,55,69,65,70
120,female,group C,bachelor's degree,standard,completed,79,92,89,70
121,male,group B,associate's degree,standard,completed,91,89,92,70
122,female,group C,some college,standard,completed,88,93,93,70
123,male,group D,high school,free/reduced,none,63,57,56,70
124,male,group E,some college,standard,none,83,80,73,70
125,female,group B,high school,standard,none,87,95,86,70
126,male,group B,some high school,standard,none,72,68,67,70
127,male,group D,some college,standard,completed,65,77,74,70
128,male,group D,master's degree,standard,none,82,82,74,70
129,female,group A,bachelor's degree,standard,none,51,49,51,70
130,male,group D,master's degree,standard,none,89,84,82,70
131,male,group C,some high school,free/reduced,completed,53,37,40,70
132,male,group E,some college,free/reduced,completed,87,74,70,70
133,female,group C,some college,standard,completed,75,81,84,70
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,70
135,male,group C,bachelor's degree,standard,none,58,55,48,70
136,male,group B,some high school,standard,completed,51,54,41,70
137,male,group E,high school,standard,none,70,55,56,70
138,female,group C,associate's degree,standard,none,59,66,67,70
139,male,group D,some college,standard,completed,71,61,69,70
140,female,group D,some high school,standard,none,76,72,71,70
141,female,group C,some college,free/reduced,none,59,62,64,70
142,female,group E,some college,free/reduced,completed,42,55,54,70
143,male,group A,high school,standard,none,57,43,47,70
144,male,group D,some college,standard,none,88,73,78,70
145,female,group C,some college,free/reduced,none,22,39,33,70
146,male,group B,some high school,standard,none,88,84,75,70
147,male,group C,associate's degree,free/reduced,none,73,68,66,70
148,female,group D,bachelor's degree,standard,completed,68,75,81,70
149,male,group E,associate's degree,free/reduced,completed,100,100,93,70
150,male,group A,some high school,standard,completed,62,67,69,70
151,male,group A,bachelor's degree,standard,none,77,67,68,70
152,female,group B,associate's degree,standard,completed,59,70,66,70
153,male,group D,bachelor's degree,standard,none,54,49,47,70
154,male,group D,some high school,standard,none,62,67,61,70
155,female,group C,some college,standard,completed,70,89,88,70
156,female,group E,high school,free/reduced,completed,66,74,78,70
157,male,group B,some college,free/reduced,none,60,60,60,70
158,female,group B,associate's degree,standard,completed,61,86,87,70
159,male,group D,associate's degree,free/reduced,none,66,62,64,70
160,male,group B,associate's degree,free/reduced,completed,82,78,74,70
161,female,group E,some college,free/reduced,completed,75,88,85,70
162,male,group B,master's degree,free/reduced,none,49,53,52,70
163,male,group C,high school,standard,none,52,53,49,70
164,female,group E,master's degree,standard,none,81,92,91,70
165,female,group C,bachelor's degree,standard,completed,96,100,100,70
166,male,group C,high school,free/reduced,completed,53,51,51,70
167,female,group B,master's degree,free/reduced,completed,58,76,78,70
168,female,group B,high school,standard,completed,68,83,78,70
169,female,group C,some college,free/reduced,completed,67,75,70,70
170,male,group A,high school,standard,completed,72,73,74,70
171,male,group E,some high school,standard,none,94,88,78,70
172,female,group D,some college,standard,none,79,86,81,70
173,female,group C,associate's degree,standard,none,63,67,70,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,70
175,female,group C,master's degree,standard,completed,81,91,87,70
176,female,group B,high school,free/reduced,completed,46,54,58,70
177,female,group C,associate's degree,standard,completed,71,77,77,70
178,female,group B,master's degree,free/reduced,completed,52,70,62,70
179,female,group D,some high school,standard,completed,97,100,100,70
180,male,group C,master's degree,free/reduced,completed,62,68,75,70
181,female,group C,some college,free/reduced,none,46,64,66,70
182,female,group E,high school,standard,none,50,50,47,70
183,female,group D,associate's degree,standard,none,65,69,70,70
184,male,group C,some high school,free/reduced,completed,45,52,49,70
185,male,group C,associate's degree,free/reduced,completed,65,67,65,70
186,male,group E,high school,standard,none,80,76,65,70
187,male,group D,some high school,standard,completed,62,66,68,70
188,male,group B,some high school,free/reduced,none,48,52,45,70
189,female,group C,bachelor's degree,standard,none,77,88,87,70
190,female,group E,associate's degree,standard,none,66,65,69,70
191,male,group D,some college,standard,completed,76,83,79,70
192,female,group B,some high school,standard,none,62,64,66,70
193,male,group D,some college,standard,completed,77,62,62,70
194,female,group C,master's degree,standard,completed,69,84,85,70
195,male,group D,associate's degree,standard,none,61,55,52,70
196,male,group C,some high school,free/reduced,completed,59,69,65,70
197,male,group E,high school,free/reduced,none,55,56,51,70
198,female,group B,some college,free/reduced,none,45,53,55,70
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,70
200,female,group C,associate's degree,standard,completed,67,84,86,70
201,female,group D,some college,free/reduced,none,65,81,77,70
202,male,group C,associate's degree,standard,none,69,77,69,70
203,female,group B,associate's degree,standard,none,57,69,68,70
204,male,group C,some college,standard,none,59,41,42,70
205,male,group D,some high school,standard,completed,74,71,78,70
206,male,group E,bachelor's degree,standard,none,82,62,62,70
207,male,group E,high school,standard,completed,81,80,76,70
208,female,group B,some college,free/reduced,none,74,81,76,70
209,female,group B,some college,free/reduced,none,58,61,66,70
210,male,group D,some high school,free/reduced,completed,80,79,79,70
211,male,group C,some college,free/reduced,none,35,28,27,70
212,female,group C,high school,free/reduced,none,42,62,60,70
213,male,group C,associate's degree,free/reduced,completed,60,51,56,70
214,male,group E,high school,standard,completed,87,91,81,70
215,male,group B,some high school,standard,completed,84,83,75,70
216,female,group E,associate's degree,free/reduced,completed,83,86,88,70
217,female,group C,high school,free/reduced,none,34,42,39,70
218,male,group B,high school,free/reduced,none,66,77,70,70
219,male,group B,some high school,standard,completed,61,56,56,70
220,female,group D,high school,standard,completed,56,68,74,70
221,male,group B,associate's degree,standard,none,87,85,73,70
222,female,group C,some high school,free/reduced,none,55,65,62,70
223,male,group D,some high school,standard,none,86,80,75,70
224,female,group B,associate's degree,standard,completed,52,66,73,70
225,female,group E,master's degree,free/reduced,none,45,56,54,70
226,female,group C,some college,standard,none,72,72,71,70
227,male,group D,high school,standard,none,57,50,54,70
228,male,group A,some high school,free/reduced,none,68,72,64,70
229,female,group C,some college,standard,completed,88,95,94,70
230,male,group D,some college,standard,none,76,64,66,70
231,male,group C,associate's degree,standard,none,46,43,42,70
232,female,group B,bachelor's degree,standard,none,67,86,83,70
233,male,group E,some high school,standard,none,92,87,78,70
234,male,group C,bachelor's degree,standard,completed,83,82,84,70
235,male,group D,associate's degree,standard,none,80,75,77,70
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,70
237,female,group D,some high school,standard,completed,64,60,74,70
238,male,group B,some college,standard,none,54,52,51,70
239,male,group C,associate's degree,standard,none,84,80,80,70
240,male,group D,high school,free/reduced,completed,73,68,66,70
241,female,group E,bachelor's degree,standard,none,80,83,83,70
242,female,group D,high school,standard,none,56,52,55,70
243,male,group E,some college,standard,none,59,51,43,70
244,male,group D,some high school,standard,none,75,74,69,70
245,male,group C,associate's degree,standard,none,85,76,71,70
246,male,group E,associate's degree,standard,none,89,76,74,70
247,female,group B,high school,standard,completed,58,70,68,70
248,female,group B,high school,standard,none,65,64,62,70
249,male,group C,high school,standard,none,68,60,53,70
250,male,group A,some high school,standard,completed,47,49,49,70
251,female,group D,some college,free/reduced,none,71,83,83,70
252,female,group B,some high school,standard,completed,60,70,70,70
253,male,group D,master's degree,standard,none,80,80,72,70
254,male,group D,high school,standard,none,54,52,52,70
255,female,group E,some college,standard,none,62,73,70,70
256,female,group C,associate's degree,free/reduced,none,64,73,68,70
257,male,group C,associate's degree,standard,completed,78,77,77,70
258,female,group B,some college,standard,none,70,75,78,70
259,female,group C,master's degree,free/reduced,completed,65,81,81,70
260,female,group C,some high school,free/reduced,completed,64,79,77,70
261,male,group C,some college,standard,completed,79,79,78,70
262,female,group C,some high school,free/reduced,none,44,50,51,70
263,female,group E,high school,standard,none,99,93,90,70
264,male,group D,high school,standard,none,76,73,68,70
265,male,group D,some high school,free/reduced,none,59,42,41,70
266,female,group C,bachelor's degree,standard,none,63,75,81,70
267,female,group D,high school,standard,none,69,72,77,70
268,female,group D,associate's degree,standard,completed,88,92,95,70
269,female,group E,some college,free/reduced,none,71,76,70,70
270,male,group C,bachelor's degree,standard,none,69,63,61,70
271,male,group C,some college,standard,none,58,49,42,70
272,female,group D,associate's degree,free/reduced,none,47,53,58,70
273,female,group D,some college,standard,none,65,70,71,70
274,male,group B,some college,standard,completed,88,85,76,70
275,male,group C,bachelor's degree,standard,none,83,78,73,70
276,female,group C,some high school,standard,completed,85,92,93,70
277,female,group E,high school,standard,completed,59,63,75,70
278,female,group C,some high school,free/reduced,none,65,86,80,70
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,70
280,male,group D,high school,standard,none,53,52,42,70
281,male,group D,high school,standard,none,45,48,46,70
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,70
283,female,group D,some college,free/reduced,completed,70,78,78,70
284,female,group B,some high school,standard,none,37,46,46,70
285,male,group B,associate's degree,standard,completed,81,82,82,70
286,male,group E,associate's degree,standard,completed,97,82,88,70
287,female,group B,some high school,standard,none,67,89,82,70
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,70
289,male,group E,some high school,standard,completed,77,76,77,70
290,male,group C,associate's degree,standard,none,76,70,68,70
291,male,group D,some high school,standard,none,86,73,70,70
292,male,group C,some high school,standard,completed,63,60,57,70
293,female,group E,bachelor's degree,standard,none,65,73,75,70
294,male,group D,high school,free/reduced,completed,78,77,80,70
295,male,group B,associate's degree,free/reduced,none,67,62,60,70
296,male,group A,some high school,standard,completed,46,41,43,70
297,male,group E,associate's degree,standard,completed,71,74,68,70
298,male,group C,high school,free/reduced,completed,40,46,50,70
299,male,group D,associate's degree,free/reduced,none,90,87,75,70
300,male,group A,some college,free/reduced,completed,81,78,81,70
301,male,group D,some high school,free/reduced,none,56,54,52,70
302,female,group C,associate's degree,standard,completed,67,84,81,70
303,male,group B,associate's degree,standard,none,80,76,64,70
304,female,group C,associate's degree,standard,completed,74,75,83,70
305,male,group A,some college,standard,none,69,67,69,70
306,male,group E,some college,standard,completed,99,87,81,70
307,male,group C,some high school,standard,none,51,52,44,70
308,female,group B,associate's degree,free/reduced,none,53,71,67,70
309,female,group D,high school,free/reduced,none,49,57,52,70
310,female,group B,associate's degree,standard,none,73,76,80,70
311,male,group B,bachelor's degree,standard,none,66,60,57,70
312,male,group D,bachelor's degree,standard,completed,67,61,68,70
313,female,group C,associate's degree,free/reduced,completed,68,67,69,70
314,female,group C,bachelor's degree,standard,completed,59,64,75,70
315,male,group C,high school,standard,none,71,66,65,70
316,female,group D,master's degree,standard,completed,77,82,91,70

# Adding a new column in an array

In [ ]:
# The dataframe that we're dealing with has 1000 rows, so we need to create an array with 1000 elements
import numpy as np

# create an array of 1000 elements
language_score = np.arange(0, 1000)
language_score

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [ ]:
# length of an array
len(language_score)

1000

In [ ]:
# Adding a new column to a dataframe
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
5,female,group B,associate's degree,standard,none,71,83,78,5
6,female,group B,some college,standard,completed,88,95,92,6
7,male,group B,some college,free/reduced,none,40,43,39,7
8,male,group D,high school,free/reduced,completed,64,64,67,8
9,female,group B,high school,free/reduced,none,38,60,50,9
10,male,group C,associate's degree,standard,none,58,54,52,10
11,male,group D,associate's degree,standard,none,40,52,43,11
12,female,group B,high school,standard,none,65,81,73,12
13,male,group A,some college,standard,completed,78,72,70,13
14,female,group A,master's degree,standard,none,50,53,58,14
15,female,group C,some high school,standard,none,69,75,78,15
16,male,group C,high school,standard,none,88,89,86,16
17,female,group B,some high school,free/reduced,none,18,32,28,17
18,male,group C,master's degree,free/reduced,completed,46,42,46,18
19,female,group C,associate's degree,free/reduced,none,54,58,61,19
20,male,group D,high school,standard,none,66,69,63,20
21,female,group B,some college,free/reduced,completed,65,75,70,21
22,male,group D,some college,standard,none,44,54,53,22
23,female,group C,some high school,standard,none,69,73,73,23
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,24
25,male,group A,master's degree,free/reduced,none,73,74,72,25
26,male,group B,some college,standard,none,69,54,55,26
27,female,group C,bachelor's degree,standard,none,67,69,75,27
28,male,group C,high school,standard,none,70,70,65,28
29,female,group D,master's degree,standard,none,62,70,75,29
30,female,group D,some college,standard,none,69,74,74,30
31,female,group B,some college,standard,none,63,65,61,31
32,female,group E,master's degree,free/reduced,none,56,72,65,32
33,male,group D,some college,standard,none,40,42,38,33
34,male,group E,some college,standard,none,97,87,82,34
35,male,group E,associate's degree,standard,completed,81,81,79,35
36,female,group D,associate's degree,standard,none,74,81,83,36
37,female,group D,some high school,free/reduced,none,50,64,59,37
38,female,group D,associate's degree,free/reduced,completed,75,90,88,38
39,male,group B,associate's degree,free/reduced,none,57,56,57,39
40,male,group C,associate's degree,free/reduced,none,55,61,54,40
41,female,group C,associate's degree,standard,none,58,73,68,41
42,female,group B,associate's degree,standard,none,53,58,65,42
43,male,group B,some college,free/reduced,completed,59,65,66,43
44,female,group E,associate's degree,free/reduced,none,50,56,54,44
45,male,group B,associate's degree,standard,none,65,54,57,45
46,female,group A,associate's degree,standard,completed,55,65,62,46
47,female,group C,high school,standard,none,66,71,76,47
48,female,group D,associate's degree,free/reduced,completed,57,74,76,48
49,male,group C,high school,standard,completed,82,84,82,49
50,male,group E,some college,standard,none,53,55,48,50
51,male,group E,associate's degree,free/reduced,completed,77,69,68,51
52,male,group C,some college,standard,none,53,44,42,52
53,male,group D,high school,standard,none,88,78,75,53
54,female,group C,some high school,free/reduced,completed,71,84,87,54
55,female,group C,high school,free/reduced,none,33,41,43,55
56,female,group E,associate's degree,standard,completed,82,85,86,56
57,male,group D,associate's degree,standard,none,52,55,49,57
58,male,group D,some college,standard,completed,58,59,58,58
59,female,group C,some high school,free/reduced,none,0,17,10,59
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,60
61,male,group A,some high school,free/reduced,none,39,39,34,61
62,male,group A,associate's degree,free/reduced,none,62,61,55,62
63,female,group C,associate's degree,standard,none,69,80,71,63
64,female,group D,some high school,standard,none,59,58,59,64
65,male,group B,some high school,standard,none,67,64,61,65
66,male,group D,some high school,free/reduced,none,45,37,37,66
67,female,group C,some college,standard,none,60,72,74,67
68,male,group B,associate's degree,free/reduced,none,61,58,56,68
69,female,group C,associate's degree,standard,none,39,64,57,69
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,71
72,female,group A,associate's degree,free/reduced,none,41,51,48,72
73,male,group C,some high school,free/reduced,none,61,57,56,73
74,male,group C,some high school,standard,none,49,49,41,74
75,male,group B,associate's degree,free/reduced,none,44,41,38,75
76,male,group E,some high school,standard,none,30,26,22,76
77,male,group A,bachelor's degree,standard,completed,80,78,81,77
78,female,group D,some high school,standard,completed,61,74,72,78
79,female,group E,master's degree,standard,none,62,68,68,79
80,female,group B,associate's degree,standard,none,47,49,50,80
81,male,group B,high school,free/reduced,none,49,45,45,81
82,male,group A,some college,free/reduced,completed,50,47,54,82
83,male,group E,associate's degree,standard,none,72,64,63,83
84,male,group D,high school,free/reduced,none,42,39,34,84
85,female,group C,some college,standard,none,73,80,82,85
86,female,group C,some college,free/reduced,none,76,83,88,86
87,female,group D,associate's degree,standard,none,71,71,74,87
88,female,group A,some college,standard,none,58,70,67,88
89,female,group D,some high school,standard,none,73,86,82,89
90,female,group C,bachelor's degree,standard,none,65,72,74,90
91,male,group C,high school,free/reduced,none,27,34,36,91
92,male,group C,high school,standard,none,71,79,71,92
93,male,group C,associate's degree,free/reduced,completed,43,45,50,93
94,female,group B,some college,standard,none,79,86,92,94
95,male,group C,associate's degree,free/reduced,completed,78,81,82,95
96,male,group B,some high school,standard,completed,65,66,62,96
97,female,group E,some college,standard,completed,63,72,70,97
98,female,group D,some college,free/reduced,none,58,67,62,98
99,female,group D,bachelor's degree,standard,none,65,67,62,99
100,male,group B,some college,standard,none,79,67,67,100
101,male,group D,bachelor's degree,standard,completed,68,74,74,101
102,female,group D,associate's degree,standard,none,85,91,89,102
103,male,group B,high school,standard,completed,60,44,47,103
104,male,group C,some college,standard,completed,98,86,90,104
105,female,group C,some college,standard,none,58,67,72,105
106,female,group D,master's degree,standard,none,87,100,100,106
107,male,group E,associate's degree,standard,completed,66,63,64,107
108,female,group B,associate's degree,free/reduced,none,52,76,70,108
109,female,group B,some high school,standard,none,70,64,72,109
110,female,group D,associate's degree,free/reduced,completed,77,89,98,110
111,male,group C,high school,standard,none,62,55,49,111
112,male,group A,associate's degree,standard,none,54,53,47,112
113,female,group D,some college,standard,none,51,58,54,113
114,female,group E,bachelor's degree,standard,completed,99,100,100,114
115,male,group C,high school,standard,none,84,77,74,115
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,116
117,female,group D,bachelor's degree,standard,none,78,82,79,117
118,female,group D,some high school,standard,none,51,63,61,118
119,female,group C,some college,standard,none,55,69,65,119
120,female,group C,bachelor's degree,standard,completed,79,92,89,120
121,male,group B,associate's degree,standard,completed,91,89,92,121
122,female,group C,some college,standard,completed,88,93,93,122
123,male,group D,high school,free/reduced,none,63,57,56,123
124,male,group E,some college,standard,none,83,80,73,124
125,female,group B,high school,standard,none,87,95,86,125
126,male,group B,some high school,standard,none,72,68,67,126
127,male,group D,some college,standard,completed,65,77,74,127
128,male,group D,master's degree,standard,none,82,82,74,128
129,female,group A,bachelor's degree,standard,none,51,49,51,129
130,male,group D,master's degree,standard,none,89,84,82,130
131,male,group C,some high school,free/reduced,completed,53,37,40,131
132,male,group E,some college,free/reduced,completed,87,74,70,132
133,female,group C,some college,standard,completed,75,81,84,133
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,134
135,male,group C,bachelor's degree,standard,none,58,55,48,135
136,male,group B,some high school,standard,completed,51,54,41,136
137,male,group E,high school,standard,none,70,55,56,137
138,female,group C,associate's degree,standard,none,59,66,67,138
139,male,group D,some college,standard,completed,71,61,69,139
140,female,group D,some high school,standard,none,76,72,71,140
141,female,group C,some college,free/reduced,none,59,62,64,141
142,female,group E,some college,free/reduced,completed,42,55,54,142
143,male,group A,high school,standard,none,57,43,47,143
144,male,group D,some college,standard,none,88,73,78,144
145,female,group C,some college,free/reduced,none,22,39,33,145
146,male,group B,some high school,standard,none,88,84,75,146
147,male,group C,associate's degree,free/reduced,none,73,68,66,147
148,female,group D,bachelor's degree,standard,completed,68,75,81,148
149,male,group E,associate's degree,free/reduced,completed,100,100,93,149
150,male,group A,some high school,standard,completed,62,67,69,150
151,male,group A,bachelor's degree,standard,none,77,67,68,151
152,female,group B,associate's degree,standard,completed,59,70,66,152
153,male,group D,bachelor's degree,standard,none,54,49,47,153
154,male,group D,some high school,standard,none,62,67,61,154
155,female,group C,some college,standard,completed,70,89,88,155
156,female,group E,high school,free/reduced,completed,66,74,78,156
157,male,group B,some college,free/reduced,none,60,60,60,157
158,female,group B,associate's degree,standard,completed,61,86,87,158
159,male,group D,associate's degree,free/reduced,none,66,62,64,159
160,male,group B,associate's degree,free/reduced,completed,82,78,74,160
161,female,group E,some college,free/reduced,completed,75,88,85,161
162,male,group B,master's degree,free/reduced,none,49,53,52,162
163,male,group C,high school,standard,none,52,53,49,163
164,female,group E,master's degree,standard,none,81,92,91,164
165,female,group C,bachelor's degree,standard,completed,96,100,100,165
166,male,group C,high school,free/reduced,completed,53,51,51,166
167,female,group B,master's degree,free/reduced,completed,58,76,78,167
168,female,group B,high school,standard,completed,68,83,78,168
169,female,group C,some college,free/reduced,completed,67,75,70,169
170,male,group A,high school,standard,completed,72,73,74,170
171,male,group E,some high school,standard,none,94,88,78,171
172,female,group D,some college,standard,none,79,86,81,172
173,female,group C,associate's degree,standard,none,63,67,70,173
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,174
175,female,group C,master's degree,standard,completed,81,91,87,175
176,female,group B,high school,free/reduced,completed,46,54,58,176
177,female,group C,associate's degree,standard,completed,71,77,77,177
178,female,group B,master's degree,free/reduced,completed,52,70,62,178
179,female,group D,some high school,standard,completed,97,100,100,179
180,male,group C,master's degree,free/reduced,completed,62,68,75,180
181,female,group C,some college,free/reduced,none,46,64,66,181
182,female,group E,high school,standard,none,50,50,47,182
183,female,group D,associate's degree,standard,none,65,69,70,183
184,male,group C,some high school,free/reduced,completed,45,52,49,184
185,male,group C,associate's degree,free/reduced,completed,65,67,65,185
186,male,group E,high school,standard,none,80,76,65,186
187,male,group D,some high school,standard,completed,62,66,68,187
188,male,group B,some high school,free/reduced,none,48,52,45,188
189,female,group C,bachelor's degree,standard,none,77,88,87,189
190,female,group E,associate's degree,standard,none,66,65,69,190
191,male,group D,some college,standard,completed,76,83,79,191
192,female,group B,some high school,standard,none,62,64,66,192
193,male,group D,some college,standard,completed,77,62,62,193
194,female,group C,master's degree,standard,completed,69,84,85,194
195,male,group D,associate's degree,standard,none,61,55,52,195
196,male,group C,some high school,free/reduced,completed,59,69,65,196
197,male,group E,high school,free/reduced,none,55,56,51,197
198,female,group B,some college,free/reduced,none,45,53,55,198
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,199
200,female,group C,associate's degree,standard,completed,67,84,86,200
201,female,group D,some college,free/reduced,none,65,81,77,201
202,male,group C,associate's degree,standard,none,69,77,69,202
203,female,group B,associate's degree,standard,none,57,69,68,203
204,male,group C,some college,standard,none,59,41,42,204
205,male,group D,some high school,standard,completed,74,71,78,205
206,male,group E,bachelor's degree,standard,none,82,62,62,206
207,male,group E,high school,standard,completed,81,80,76,207
208,female,group B,some college,free/reduced,none,74,81,76,208
209,female,group B,some college,free/reduced,none,58,61,66,209
210,male,group D,some high school,free/reduced,completed,80,79,79,210
211,male,group C,some college,free/reduced,none,35,28,27,211
212,female,group C,high school,free/reduced,none,42,62,60,212
213,male,group C,associate's degree,free/reduced,completed,60,51,56,213
214,male,group E,high school,standard,completed,87,91,81,214
215,male,group B,some high school,standard,completed,84,83,75,215
216,female,group E,associate's degree,free/reduced,completed,83,86,88,216
217,female,group C,high school,free/reduced,none,34,42,39,217
218,male,group B,high school,free/reduced,none,66,77,70,218
219,male,group B,some high school,standard,completed,61,56,56,219
220,female,group D,high school,standard,completed,56,68,74,220
221,male,group B,associate's degree,standard,none,87,85,73,221
222,female,group C,some high school,free/reduced,none,55,65,62,222
223,male,group D,some high school,standard,none,86,80,75,223
224,female,group B,associate's degree,standard,completed,52,66,73,224
225,female,group E,master's degree,free/reduced,none,45,56,54,225
226,female,group C,some college,standard,none,72,72,71,226
227,male,group D,high school,standard,none,57,50,54,227
228,male,group A,some high school,free/reduced,none,68,72,64,228
229,female,group C,some college,standard,completed,88,95,94,229
230,male,group D,some college,standard,none,76,64,66,230
231,male,group C,associate's degree,standard,none,46,43,42,231
232,female,group B,bachelor's degree,standard,none,67,86,83,232
233,male,group E,some high school,standard,none,92,87,78,233
234,male,group C,bachelor's degree,standard,completed,83,82,84,234
235,male,group D,associate's degree,standard,none,80,75,77,235
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,236
237,female,group D,some high school,standard,completed,64,60,74,237
238,male,group B,some college,standard,none,54,52,51,238
239,male,group C,associate's degree,standard,none,84,80,80,239
240,male,group D,high school,free/reduced,completed,73,68,66,240
241,female,group E,bachelor's degree,standard,none,80,83,83,241
242,female,group D,high school,standard,none,56,52,55,242
243,male,group E,some college,standard,none,59,51,43,243
244,male,group D,some high school,standard,none,75,74,69,244
245,male,group C,associate's degree,standard,none,85,76,71,245
246,male,group E,associate's degree,standard,none,89,76,74,246
247,female,group B,high school,standard,completed,58,70,68,247
248,female,group B,high school,standard,none,65,64,62,248
249,male,group C,high school,standard,none,68,60,53,249
250,male,group A,some high school,standard,completed,47,49,49,250
251,female,group D,some college,free/reduced,none,71,83,83,251
252,female,group B,some high school,standard,completed,60,70,70,252
253,male,group D,master's degree,standard,none,80,80,72,253
254,male,group D,high school,standard,none,54,52,52,254
255,female,group E,some college,standard,none,62,73,70,255
256,female,group C,associate's degree,free/reduced,none,64,73,68,256
257,male,group C,associate's degree,standard,completed,78,77,77,257
258,female,group B,some college,standard,none,70,75,78,258
259,female,group C,master's degree,free/reduced,completed,65,81,81,259
260,female,group C,some high school,free/reduced,completed,64,79,77,260
261,male,group C,some college,standard,completed,79,79,78,261
262,female,group C,some high school,free/reduced,none,44,50,51,262
263,female,group E,high school,standard,none,99,93,90,263
264,male,group D,high school,standard,none,76,73,68,264
265,male,group D,some high school,free/reduced,none,59,42,41,265
266,female,group C,bachelor's degree,standard,none,63,75,81,266
267,female,group D,high school,standard,none,69,72,77,267
268,female,group D,associate's degree,standard,completed,88,92,95,268
269,female,group E,some college,free/reduced,none,71,76,70,269
270,male,group C,bachelor's degree,standard,none,69,63,61,270
271,male,group C,some college,standard,none,58,49,42,271
272,female,group D,associate's degree,free/reduced,none,47,53,58,272
273,female,group D,some college,standard,none,65,70,71,273
274,male,group B,some college,standard,completed,88,85,76,274
275,male,group C,bachelor's degree,standard,none,83,78,73,275
276,female,group C,some high school,standard,completed,85,92,93,276
277,female,group E,high school,standard,completed,59,63,75,277
278,female,group C,some high school,free/reduced,none,65,86,80,278
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,279
280,male,group D,high school,standard,none,53,52,42,280
281,male,group D,high school,standard,none,45,48,46,281
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,282
283,female,group D,some college,free/reduced,completed,70,78,78,283
284,female,group B,some high school,standard,none,37,46,46,284
285,male,group B,associate's degree,standard,completed,81,82,82,285
286,male,group E,associate's degree,standard,completed,97,82,88,286
287,female,group B,some high school,standard,none,67,89,82,287
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,288
289,male,group E,some high school,standard,completed,77,76,77,289
290,male,group C,associate's degree,standard,none,76,70,68,290
291,male,group D,some high school,standard,none,86,73,70,291
292,male,group C,some high school,standard,completed,63,60,57,292
293,female,group E,bachelor's degree,standard,none,65,73,75,293
294,male,group D,high school,free/reduced,completed,78,77,80,294
295,male,group B,associate's degree,free/reduced,none,67,62,60,295
296,male,group A,some high school,standard,completed,46,41,43,296
297,male,group E,associate's degree,standard,completed,71,74,68,297
298,male,group C,high school,free/reduced,completed,40,46,50,298
299,male,group D,associate's degree,free/reduced,none,90,87,75,299
300,male,group A,some college,free/reduced,completed,81,78,81,300
301,male,group D,some high school,free/reduced,none,56,54,52,301
302,female,group C,associate's degree,standard,completed,67,84,81,302
303,male,group B,associate's degree,standard,none,80,76,64,303
304,female,group C,associate's degree,standard,completed,74,75,83,304
305,male,group A,some college,standard,none,69,67,69,305
306,male,group E,some college,standard,completed,99,87,81,306
307,male,group C,some high school,standard,none,51,52,44,307
308,female,group B,associate's degree,free/reduced,none,53,71,67,308
309,female,group D,high school,free/reduced,none,49,57,52,309
310,female,group B,associate's degree,standard,none,73,76,80,310
311,male,group B,bachelor's degree,standard,none,66,60,57,311
312,male,group D,bachelor's degree,standard,completed,67,61,68,312

In [ ]:
# create random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size=1000)

In [ ]:
# min value inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

np.int32(99)

In [ ]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,94
1,female,group C,some college,standard,completed,69,90,88,53
2,female,group B,master's degree,standard,none,90,95,93,12
3,male,group A,associate's degree,free/reduced,none,47,57,44,5
4,male,group C,some college,standard,none,76,78,75,22
5,female,group B,associate's degree,standard,none,71,83,78,80
6,female,group B,some college,standard,completed,88,95,92,77
7,male,group B,some college,free/reduced,none,40,43,39,72
8,male,group D,high school,free/reduced,completed,64,64,67,17
9,female,group B,high school,free/reduced,none,38,60,50,6
10,male,group C,associate's degree,standard,none,58,54,52,39
11,male,group D,associate's degree,standard,none,40,52,43,40
12,female,group B,high school,standard,none,65,81,73,61
13,male,group A,some college,standard,completed,78,72,70,70
14,female,group A,master's degree,standard,none,50,53,58,45
15,female,group C,some high school,standard,none,69,75,78,89
16,male,group C,high school,standard,none,88,89,86,27
17,female,group B,some high school,free/reduced,none,18,32,28,30
18,male,group C,master's degree,free/reduced,completed,46,42,46,95
19,female,group C,associate's degree,free/reduced,none,54,58,61,43
20,male,group D,high school,standard,none,66,69,63,12
21,female,group B,some college,free/reduced,completed,65,75,70,46
22,male,group D,some college,standard,none,44,54,53,4
23,female,group C,some high school,standard,none,69,73,73,67
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,19
25,male,group A,master's degree,free/reduced,none,73,74,72,38
26,male,group B,some college,standard,none,69,54,55,59
27,female,group C,bachelor's degree,standard,none,67,69,75,20
28,male,group C,high school,standard,none,70,70,65,23
29,female,group D,master's degree,standard,none,62,70,75,45
30,female,group D,some college,standard,none,69,74,74,51
31,female,group B,some college,standard,none,63,65,61,35
32,female,group E,master's degree,free/reduced,none,56,72,65,97
33,male,group D,some college,standard,none,40,42,38,16
34,male,group E,some college,standard,none,97,87,82,14
35,male,group E,associate's degree,standard,completed,81,81,79,81
36,female,group D,associate's degree,standard,none,74,81,83,95
37,female,group D,some high school,free/reduced,none,50,64,59,85
38,female,group D,associate's degree,free/reduced,completed,75,90,88,53
39,male,group B,associate's degree,free/reduced,none,57,56,57,60
40,male,group C,associate's degree,free/reduced,none,55,61,54,30
41,female,group C,associate's degree,standard,none,58,73,68,23
42,female,group B,associate's degree,standard,none,53,58,65,64
43,male,group B,some college,free/reduced,completed,59,65,66,7
44,female,group E,associate's degree,free/reduced,none,50,56,54,1
45,male,group B,associate's degree,standard,none,65,54,57,60
46,female,group A,associate's degree,standard,completed,55,65,62,4
47,female,group C,high school,standard,none,66,71,76,3
48,female,group D,associate's degree,free/reduced,completed,57,74,76,29
49,male,group C,high school,standard,completed,82,84,82,56
50,male,group E,some college,standard,none,53,55,48,37
51,male,group E,associate's degree,free/reduced,completed,77,69,68,61
52,male,group C,some college,standard,none,53,44,42,62
53,male,group D,high school,standard,none,88,78,75,30
54,female,group C,some high school,free/reduced,completed,71,84,87,51
55,female,group C,high school,free/reduced,none,33,41,43,23
56,female,group E,associate's degree,standard,completed,82,85,86,96
57,male,group D,associate's degree,standard,none,52,55,49,23
58,male,group D,some college,standard,completed,58,59,58,64
59,female,group C,some high school,free/reduced,none,0,17,10,33
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,23
61,male,group A,some high school,free/reduced,none,39,39,34,45
62,male,group A,associate's degree,free/reduced,none,62,61,55,69
63,female,group C,associate's degree,standard,none,69,80,71,51
64,female,group D,some high school,standard,none,59,58,59,66
65,male,group B,some high school,standard,none,67,64,61,27
66,male,group D,some high school,free/reduced,none,45,37,37,63
67,female,group C,some college,standard,none,60,72,74,77
68,male,group B,associate's degree,free/reduced,none,61,58,56,27
69,female,group C,associate's degree,standard,none,39,64,57,50
70,female,group D,some college,free/reduced,completed,58,63,73,16
71,male,group D,some college,standard,completed,63,55,63,35
72,female,group A,associate's degree,free/reduced,none,41,51,48,45
73,male,group C,some high school,free/reduced,none,61,57,56,84
74,male,group C,some high school,standard,none,49,49,41,21
75,male,group B,associate's degree,free/reduced,none,44,41,38,29
76,male,group E,some high school,standard,none,30,26,22,51
77,male,group A,bachelor's degree,standard,completed,80,78,81,76
78,female,group D,some high school,standard,completed,61,74,72,97
79,female,group E,master's degree,standard,none,62,68,68,35
80,female,group B,associate's degree,standard,none,47,49,50,87
81,male,group B,high school,free/reduced,none,49,45,45,28
82,male,group A,some college,free/reduced,completed,50,47,54,23
83,male,group E,associate's degree,standard,none,72,64,63,18
84,male,group D,high school,free/reduced,none,42,39,34,7
85,female,group C,some college,standard,none,73,80,82,92
86,female,group C,some college,free/reduced,none,76,83,88,70
87,female,group D,associate's degree,standard,none,71,71,74,39
88,female,group A,some college,standard,none,58,70,67,93
89,female,group D,some high school,standard,none,73,86,82,15
90,female,group C,bachelor's degree,standard,none,65,72,74,43
91,male,group C,high school,free/reduced,none,27,34,36,17
92,male,group C,high school,standard,none,71,79,71,25
93,male,group C,associate's degree,free/reduced,completed,43,45,50,45
94,female,group B,some college,standard,none,79,86,92,83
95,male,group C,associate's degree,free/reduced,completed,78,81,82,30
96,male,group B,some high school,standard,completed,65,66,62,93
97,female,group E,some college,standard,completed,63,72,70,45
98,female,group D,some college,free/reduced,none,58,67,62,59
99,female,group D,bachelor's degree,standard,none,65,67,62,68
100,male,group B,some college,standard,none,79,67,67,10
101,male,group D,bachelor's degree,standard,completed,68,74,74,7
102,female,group D,associate's degree,standard,none,85,91,89,67
103,male,group B,high school,standard,completed,60,44,47,11
104,male,group C,some college,standard,completed,98,86,90,92
105,female,group C,some college,standard,none,58,67,72,42
106,female,group D,master's degree,standard,none,87,100,100,45
107,male,group E,associate's degree,standard,completed,66,63,64,11
108,female,group B,associate's degree,free/reduced,none,52,76,70,56
109,female,group B,some high school,standard,none,70,64,72,25
110,female,group D,associate's degree,free/reduced,completed,77,89,98,55
111,male,group C,high school,standard,none,62,55,49,64
112,male,group A,associate's degree,standard,none,54,53,47,71
113,female,group D,some college,standard,none,51,58,54,8
114,female,group E,bachelor's degree,standard,completed,99,100,100,11
115,male,group C,high school,standard,none,84,77,74,90
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,52
117,female,group D,bachelor's degree,standard,none,78,82,79,41
118,female,group D,some high school,standard,none,51,63,61,59
119,female,group C,some college,standard,none,55,69,65,26
120,female,group C,bachelor's degree,standard,completed,79,92,89,35
121,male,group B,associate's degree,standard,completed,91,89,92,74
122,female,group C,some college,standard,completed,88,93,93,79
123,male,group D,high school,free/reduced,none,63,57,56,51
124,male,group E,some college,standard,none,83,80,73,27
125,female,group B,high school,standard,none,87,95,86,30
126,male,group B,some high school,standard,none,72,68,67,20
127,male,group D,some college,standard,completed,65,77,74,20
128,male,group D,master's degree,standard,none,82,82,74,29
129,female,group A,bachelor's degree,standard,none,51,49,51,87
130,male,group D,master's degree,standard,none,89,84,82,16
131,male,group C,some high school,free/reduced,completed,53,37,40,5
132,male,group E,some college,free/reduced,completed,87,74,70,36
133,female,group C,some college,standard,completed,75,81,84,54
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,63
135,male,group C,bachelor's degree,standard,none,58,55,48,76
136,male,group B,some high school,standard,completed,51,54,41,71
137,male,group E,high school,standard,none,70,55,56,26
138,female,group C,associate's degree,standard,none,59,66,67,75
139,male,group D,some college,standard,completed,71,61,69,36
140,female,group D,some high school,standard,none,76,72,71,14
141,female,group C,some college,free/reduced,none,59,62,64,26
142,female,group E,some college,free/reduced,completed,42,55,54,43
143,male,group A,high school,standard,none,57,43,47,79
144,male,group D,some college,standard,none,88,73,78,82
145,female,group C,some college,free/reduced,none,22,39,33,13
146,male,group B,some high school,standard,none,88,84,75,65
147,male,group C,associate's degree,free/reduced,none,73,68,66,69
148,female,group D,bachelor's degree,standard,completed,68,75,81,43
149,male,group E,associate's degree,free/reduced,completed,100,100,93,79
150,male,group A,some high school,standard,completed,62,67,69,82
151,male,group A,bachelor's degree,standard,none,77,67,68,48
152,female,group B,associate's degree,standard,completed,59,70,66,51
153,male,group D,bachelor's degree,standard,none,54,49,47,66
154,male,group D,some high school,standard,none,62,67,61,14
155,female,group C,some college,standard,completed,70,89,88,1
156,female,group E,high school,free/reduced,completed,66,74,78,72
157,male,group B,some college,free/reduced,none,60,60,60,11
158,female,group B,associate's degree,standard,completed,61,86,87,60
159,male,group D,associate's degree,free/reduced,none,66,62,64,99
160,male,group B,associate's degree,free/reduced,completed,82,78,74,44
161,female,group E,some college,free/reduced,completed,75,88,85,36
162,male,group B,master's degree,free/reduced,none,49,53,52,89
163,male,group C,high school,standard,none,52,53,49,33
164,female,group E,master's degree,standard,none,81,92,91,71
165,female,group C,bachelor's degree,standard,completed,96,100,100,94
166,male,group C,high school,free/reduced,completed,53,51,51,77
167,female,group B,master's degree,free/reduced,completed,58,76,78,40
168,female,group B,high school,standard,completed,68,83,78,56
169,female,group C,some college,free/reduced,completed,67,75,70,98
170,male,group A,high school,standard,completed,72,73,74,63
171,male,group E,some high school,standard,none,94,88,78,33
172,female,group D,some college,standard,none,79,86,81,48
173,female,group C,associate's degree,standard,none,63,67,70,18
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,54
175,female,group C,master's degree,standard,completed,81,91,87,79
176,female,group B,high school,free/reduced,completed,46,54,58,40
177,female,group C,associate's degree,standard,completed,71,77,77,87
178,female,group B,master's degree,free/reduced,completed,52,70,62,80
179,female,group D,some high school,standard,completed,97,100,100,92
180,male,group C,master's degree,free/reduced,completed,62,68,75,23
181,female,group C,some college,free/reduced,none,46,64,66,26
182,female,group E,high school,standard,none,50,50,47,17
183,female,group D,associate's degree,standard,none,65,69,70,90
184,male,group C,some high school,free/reduced,completed,45,52,49,63
185,male,group C,associate's degree,free/reduced,completed,65,67,65,60
186,male,group E,high school,standard,none,80,76,65,22
187,male,group D,some high school,standard,completed,62,66,68,33
188,male,group B,some high school,free/reduced,none,48,52,45,95
189,female,group C,bachelor's degree,standard,none,77,88,87,92
190,female,group E,associate's degree,standard,none,66,65,69,34
191,male,group D,some college,standard,completed,76,83,79,94
192,female,group B,some high school,standard,none,62,64,66,99
193,male,group D,some college,standard,completed,77,62,62,35
194,female,group C,master's degree,standard,completed,69,84,85,63
195,male,group D,associate's degree,standard,none,61,55,52,56
196,male,group C,some high school,free/reduced,completed,59,69,65,65
197,male,group E,high school,free/reduced,none,55,56,51,76
198,female,group B,some college,free/reduced,none,45,53,55,62
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,34
200,female,group C,associate's degree,standard,completed,67,84,86,10
201,female,group D,some college,free/reduced,none,65,81,77,79
202,male,group C,associate's degree,standard,none,69,77,69,23
203,female,group B,associate's degree,standard,none,57,69,68,4
204,male,group C,some college,standard,none,59,41,42,25
205,male,group D,some high school,standard,completed,74,71,78,38
206,male,group E,bachelor's degree,standard,none,82,62,62,5
207,male,group E,high school,standard,completed,81,80,76,46
208,female,group B,some college,free/reduced,none,74,81,76,25
209,female,group B,some college,free/reduced,none,58,61,66,53
210,male,group D,some high school,free/reduced,completed,80,79,79,56
211,male,group C,some college,free/reduced,none,35,28,27,3
212,female,group C,high school,free/reduced,none,42,62,60,55
213,male,group C,associate's degree,free/reduced,completed,60,51,56,5
214,male,group E,high school,standard,completed,87,91,81,33
215,male,group B,some high school,standard,completed,84,83,75,43
216,female,group E,associate's degree,free/reduced,completed,83,86,88,31
217,female,group C,high school,free/reduced,none,34,42,39,92
218,male,group B,high school,free/reduced,none,66,77,70,29
219,male,group B,some high school,standard,completed,61,56,56,10
220,female,group D,high school,standard,completed,56,68,74,54
221,male,group B,associate's degree,standard,none,87,85,73,51
222,female,group C,some high school,free/reduced,none,55,65,62,52
223,male,group D,some high school,standard,none,86,80,75,26
224,female,group B,associate's degree,standard,completed,52,66,73,60
225,female,group E,master's degree,free/reduced,none,45,56,54,60
226,female,group C,some college,standard,none,72,72,71,10
227,male,group D,high school,standard,none,57,50,54,35
228,male,group A,some high school,free/reduced,none,68,72,64,62
229,female,group C,some college,standard,completed,88,95,94,99
230,male,group D,some college,standard,none,76,64,66,92
231,male,group C,associate's degree,standard,none,46,43,42,62
232,female,group B,bachelor's degree,standard,none,67,86,83,51
233,male,group E,some high school,standard,none,92,87,78,4
234,male,group C,bachelor's degree,standard,completed,83,82,84,70
235,male,group D,associate's degree,standard,none,80,75,77,67
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,89
237,female,group D,some high school,standard,completed,64,60,74,30
238,male,group B,some college,standard,none,54,52,51,52
239,male,group C,associate's degree,standard,none,84,80,80,33
240,male,group D,high school,free/reduced,completed,73,68,66,8
241,female,group E,bachelor's degree,standard,none,80,83,83,68
242,female,group D,high school,standard,none,56,52,55,96
243,male,group E,some college,standard,none,59,51,43,7
244,male,group D,some high school,standard,none,75,74,69,41
245,male,group C,associate's degree,standard,none,85,76,71,85
246,male,group E,associate's degree,standard,none,89,76,74,22
247,female,group B,high school,standard,completed,58,70,68,19
248,female,group B,high school,standard,none,65,64,62,43
249,male,group C,high school,standard,none,68,60,53,52
250,male,group A,some high school,standard,completed,47,49,49,63
251,female,group D,some college,free/reduced,none,71,83,83,27
252,female,group B,some high school,standard,completed,60,70,70,18
253,male,group D,master's degree,standard,none,80,80,72,15
254,male,group D,high school,standard,none,54,52,52,65
255,female,group E,some college,standard,none,62,73,70,94
256,female,group C,associate's degree,free/reduced,none,64,73,68,93
257,male,group C,associate's degree,standard,completed,78,77,77,42
258,female,group B,some college,standard,none,70,75,78,50
259,female,group C,master's degree,free/reduced,completed,65,81,81,4
260,female,group C,some high school,free/reduced,completed,64,79,77,22
261,male,group C,some college,standard,completed,79,79,78,18
262,female,group C,some high school,free/reduced,none,44,50,51,64
263,female,group E,high school,standard,none,99,93,90,11
264,male,group D,high school,standard,none,76,73,68,37
265,male,group D,some high school,free/reduced,none,59,42,41,8
266,female,group C,bachelor's degree,standard,none,63,75,81,99
267,female,group D,high school,standard,none,69,72,77,45
268,female,group D,associate's degree,standard,completed,88,92,95,15
269,female,group E,some college,free/reduced,none,71,76,70,50
270,male,group C,bachelor's degree,standard,none,69,63,61,46
271,male,group C,some college,standard,none,58,49,42,25
272,female,group D,associate's degree,free/reduced,none,47,53,58,79
273,female,group D,some college,standard,none,65,70,71,19
274,male,group B,some college,standard,completed,88,85,76,2
275,male,group C,bachelor's degree,standard,none,83,78,73,27
276,female,group C,some high school,standard,completed,85,92,93,51
277,female,group E,high school,standard,completed,59,63,75,55
278,female,group C,some high school,free/reduced,none,65,86,80,63
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,28
280,male,group D,high school,standard,none,53,52,42,65
281,male,group D,high school,standard,none,45,48,46,58
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,7
283,female,group D,some college,free/reduced,completed,70,78,78,77
284,female,group B,some high school,standard,none,37,46,46,52
285,male,group B,associate's degree,standard,completed,81,82,82,43
286,male,group E,associate's degree,standard,completed,97,82,88,78
287,female,group B,some high school,standard,none,67,89,82,88
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,33
289,male,group E,some high school,standard,completed,77,76,77,93
290,male,group C,associate's degree,standard,none,76,70,68,52
291,male,group D,some high school,standard,none,86,73,70,66
292,male,group C,some high school,standard,completed,63,60,57,68
293,female,group E,bachelor's degree,standard,none,65,73,75,76
294,male,group D,high school,free/reduced,completed,78,77,80,18
295,male,group B,associate's degree,free/reduced,none,67,62,60,41
296,male,group A,some high school,standard,completed,46,41,43,46
297,male,group E,associate's degree,standard,completed,71,74,68,20
298,male,group C,high school,free/reduced,completed,40,46,50,83
299,male,group D,associate's degree,free/reduced,none,90,87,75,26
300,male,group A,some college,free/reduced,completed,81,78,81,15
301,male,group D,some high school,free/reduced,none,56,54,52,67
302,female,group C,associate's degree,standard,completed,67,84,81,73
303,male,group B,associate's degree,standard,none,80,76,64,13
304,female,group C,associate's degree,standard,completed,74,75,83,30
305,male,group A,some college,standard,none,69,67,69,5
306,male,group E,some college,standard,completed,99,87,81,44
307,male,group C,some high school,standard,none,51,52,44,11
308,female,group B,associate's degree,free/reduced,none,53,71,67,31
309,female,group D,high school,free/reduced,none,49,57,52,14
310,female,group B,associate's degree,standard,none,73,76,80,78
311,male,group B,bachelor's degree,standard,none,66,60,57,40
312,male,group D,bachelor's degree,standard,completed,67,61,68,46
313,female,group C,associate's degree,free/reduced,completed,68,67,69,84
314,female,group C,bachelor's degree,standard,completed,59,64,75,16
315,male,group C,high school,standard,none,71,66,65,3
316,female,group D,master's degree,standard,completed,77,82,91,10

In [ ]:
df_exams.describe()

In [ ]:
df_exams.dtypes